# Generated by Django 5.1.5 on 2025-03-26 17:31

import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Researcher', 'Researcher')], max_length=50)),
                ('pan', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=255)),
                ('programme_code', models.CharField(max_length=20)),
                ('num_seats', models.PositiveIntegerField()),
                ('num_applications', models.PositiveIntegerField()),
                ('num_students_admitted', models.PositiveIntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_ratios', to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Course')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('year_of_introduction', models.PositiveIntegerField(verbose_name='Year of Introduction')),
                ('activities', models.TextField(verbose_name='Employability/Skill Development Activities')),
                ('document', models.FileField(blank=True, null=True, upload_to='course_documents/', verbose_name='Relevant Document')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='AwardRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_title', models.CharField(max_length=255)),
                ('awardee_name', models.CharField(max_length=255)),
                ('awarding_agency', models.CharField(max_length=255)),
                ('award_year', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Institution', 'Institution'), ('Teacher', 'Teacher'), ('Research Scholar', 'Research Scholar'), ('Student', 'Student')], max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='awards/', validators=[project.models.validate_file_size, project.models.validate_file_extension])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('programme_name', models.CharField(max_length=255)),
                ('sc_earmarked', models.IntegerField(default=0)),
                ('st_earmarked', models.IntegerField(default=0)),
                ('obc_earmarked', models.IntegerField(default=0)),
                ('gen_earmarked', models.IntegerField(default=0)),
                ('others_earmarked', models.IntegerField(default=0)),
                ('sc_admitted', models.IntegerField(default=0)),
                ('st_admitted', models.IntegerField(default=0)),
                ('obc_admitted', models.IntegerField(default=0)),
                ('gen_admitted', models.IntegerField(default=0)),
                ('others_admitted', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('budget_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenditure_infra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenditure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('academic_facilities', models.DecimalField(decimal_places=2, max_digits=12)),
                ('physical_facilities', models.DecimalField(decimal_places=2, max_digits=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='ICTFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=20)),
                ('ict_facility', models.TextField()),
                ('geo_tagged_photo', models.ImageField(blank=True, null=True, upload_to='ict_photos/', validators=[project.models.validate_file_size])),
                ('master_timetable', models.FileField(blank=True, null=True, upload_to='timetables/', validators=[project.models.validate_file_size])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('resource_name', models.CharField(max_length=100)),
                ('expenditure_journals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expenditure_other_resources', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='library_documents/', validators=[project.models.validate_file_size, project.models.validate_file_extension])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patenter_name', models.CharField(max_length=255)),
                ('patent_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('award_year', models.PositiveIntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='patents/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='PhDAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_name', models.CharField(max_length=255)),
                ('guides', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('registration_year', models.PositiveIntegerField()),
                ('award_year', models.PositiveIntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='phdaward/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phds', to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_code', models.CharField(max_length=50, unique=True)),
                ('programme_name', models.CharField(max_length=255)),
                ('year_of_introduction', models.IntegerField()),
                ('cbcs_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('year_of_cbcs_implementation', models.IntegerField(blank=True, null=True)),
                ('year_of_revision', models.IntegerField(blank=True, null=True)),
                ('content_update_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('document_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255)),
                ('funding_agency', models.CharField(max_length=255)),
                ('grant_type', models.CharField(choices=[('Government', 'Government'), ('Non-Government', 'Non-Government')], max_length=20)),
                ('year_of_award', models.PositiveIntegerField()),
                ('funds_provided', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('Months', 'Months'), ('Years', 'Years')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('investigators', models.ManyToManyField(related_name='grants', to='project.investigator')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of the Paper')),
                ('authors', models.TextField(verbose_name='Name of the Author(s)')),
                ('journal', models.CharField(max_length=255, verbose_name='Name of the Journal')),
                ('year', models.PositiveIntegerField(verbose_name='Year of Publication')),
                ('issn', models.CharField(max_length=15, verbose_name='ISSN Number')),
                ('ugc_link', models.URLField(blank=True, null=True, verbose_name='UGC Recognition Link')),
                ('document', models.FileField(blank=True, null=True, upload_to='research_paper/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_papers', to='project.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=100, verbose_name='Programme Name')),
                ('programme_code', models.CharField(max_length=20, verbose_name='Programme Code')),
                ('students', models.TextField(verbose_name='List of Students')),
                ('document', models.FileField(blank=True, null=True, upload_to='project_documents/', verbose_name='Supporting Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='FullTimeTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_year', models.CharField(max_length=255, verbose_name='Qualification (Ph.D./D.M/M.Ch./D.N.B Superspeciality/D.Sc./D’Lit.) and Year of Obtaining')),
                ('is_research_guide', models.BooleanField(default=False, verbose_name='Whether Recognised as Research Guide')),
                ('year_of_recognition', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Recognition as Research Guide')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher', verbose_name='Name of Full-Time Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='EContentDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('launch_date', models.DateField()),
                ('document_link', models.FileField(blank=True, null=True, upload_to='econtent_documents/', validators=[project.models.validate_file_size, project.models.validate_file_extension])),
                ('facility_available', models.TextField()),
                ('video_link', models.URLField(blank=True, help_text='Provide link to video.', null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='Title of the Book/Chapter')),
                ('paper_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the Paper')),
                ('proceedings_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the Proceedings')),
                ('conference_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of the Conference')),
                ('national_international', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=50, verbose_name='National / International')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Year of Publication')),
                ('isbn_issn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN/ISSN')),
                ('affiliating_institute', models.CharField(blank=True, max_length=255, null=True, verbose_name='Affiliating Institute')),
                ('publisher', models.CharField(max_length=255, verbose_name='Publisher')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher', verbose_name='Name of the Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAgainstSanctionedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_appointment', models.PositiveIntegerField(verbose_name='Year of Appointment')),
                ('nature_of_appointment', models.CharField(choices=[('Against Sanctioned Post', 'Against Sanctioned Post'), ('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=255, verbose_name='Nature of Appointment')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Total Years of Experience in the Same Institution')),
                ('still_serving', models.CharField(max_length=255, verbose_name='Is the teacher still serving / Last year of service')),
                ('last_year_of_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last Year of Service')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher', verbose_name='Full-Time Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('recognition_level', models.CharField(choices=[('International', 'International'), ('National', 'National'), ('State', 'State'), ('Institutional', 'Institutional')], max_length=50)),
                ('year_of_award', models.PositiveIntegerField()),
                ('awarding_agency', models.CharField(max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_year', models.CharField(max_length=255, verbose_name='Qualification and Year of Obtaining')),
                ('is_research_guide', models.BooleanField(default=False, verbose_name='Recognised as Research Guide')),
                ('year_of_recognition', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Recognition as Research Guide')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_records', to='project.teacher', verbose_name='Teacher Name')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherServingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_year', models.PositiveIntegerField(verbose_name='Appointment Year')),
                ('nature_of_appointment', models.CharField(max_length=255, verbose_name='Nature of Appointment')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('is_serving', models.BooleanField(default=True, verbose_name='Is Still Serving?')),
                ('last_year_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last Year of Service')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_posts', to='project.teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_scholar', models.BooleanField(default=False)),
                ('is_department_staff', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.department')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='project.userprofile'),
        ),
        migrations.CreateModel(
            name='ValueAddedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('code', models.CharField(max_length=20, verbose_name='Course Code')),
                ('year_of_offering', models.PositiveIntegerField(verbose_name='Year of Offering')),
                ('times_offered', models.PositiveIntegerField(default=1, verbose_name='Number of Times Offered')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration (e.g., 30 Hours)')),
                ('students_enrolled', models.PositiveIntegerField(verbose_name='Students Enrolled')),
                ('students_completed', models.PositiveIntegerField(verbose_name='Students Completed')),
                ('document', models.FileField(blank=True, null=True, upload_to='course_documents/', verbose_name='Supporting Document')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='project.department', verbose_name='Department')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_profile'),
        ),
    ]
