# Generated by Django 5.1.5 on 2025-02-11 12:38

import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('resource_name', models.CharField(max_length=100)),
                ('expenditure_journals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenditure_other_resources', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('document', models.FileField(upload_to='library_documents/', validators=[project.models.validate_file_size, project.models.validate_file_extension])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
            ],
        ),
    ]
