# Generated by Django 5.1.5 on 2025-02-14 06:48

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictfacility',
            name='geo_tagged_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ict_photos/', validators=[project.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='ictfacility',
            name='master_timetable',
            field=models.FileField(blank=True, null=True, upload_to='timetables/', validators=[project.models.validate_file_size]),
        ),
    ]
