# Generated by Django 5.1.5 on 2025-02-11 16:29

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryresource',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='library_documents/', validators=[project.models.validate_file_size, project.models.validate_file_extension]),
        ),
    ]
