# Generated by Django 5.1.5 on 2025-02-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_teacher_econtentdevelopment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.AlterField(
            model_name='econtentdevelopment',
            name='facility_available',
            field=models.JSONField(default=list, help_text='List of facilities available'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='expenditure_journals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='expenditure_other_resources',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department'),
        ),
    ]
