# Generated by Django 5.1.5 on 2025-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_department_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econtentdevelopment',
            name='facility_available',
            field=models.CharField(default='', help_text='Comma-separated list of facilities available', max_length=255),
        ),
    ]
