# Generated by Django 5.1.5 on 2025-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_econtentdevelopment_facility_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econtentdevelopment',
            name='facility_available',
            field=models.TextField(),
        ),
    ]
