# Generated by Django 5.1.5 on 2025-02-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_econtentdevelopment_facility_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('budget_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenditure_infra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenditure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('academic_facilities', models.DecimalField(decimal_places=2, max_digits=12)),
                ('physical_facilities', models.DecimalField(decimal_places=2, max_digits=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
            ],
        ),
    ]
