# Generated by Django 5.1.5 on 2025-02-26 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_teacher_department_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('recognition_level', models.CharField(choices=[('International', 'International'), ('National', 'National'), ('State', 'State'), ('Institutional', 'Institutional')], max_length=50)),
                ('year_of_award', models.PositiveIntegerField()),
                ('awarding_agency', models.CharField(max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher')),
            ],
        ),
    ]
