# Generated by Django 5.1.5 on 2025-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_teacheraward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='total_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
