# Generated by Django 5.1.5 on 2025-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_expenditure_total_expenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='total_expenditure',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
