# Generated by Django 5.1.5 on 2025-02-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_expenditure_total_expenditure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255)),
                ('funding_agency', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Government', 'Government'), ('Non-Government', 'Non-Government')], max_length=20)),
                ('year_of_award', models.IntegerField()),
                ('funds_provided', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(choices=[('Months', 'Months'), ('Years', 'Years')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigators', to='project.researchgrant')),
            ],
        ),
    ]
