# Generated by Django 5.1.5 on 2025-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_researchgrant_investigator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator',
            name='grant',
        ),
        migrations.AddField(
            model_name='researchgrant',
            name='investigators',
            field=models.ManyToManyField(related_name='grants', to='project.investigator'),
        ),
    ]
