# Generated by Django 5.1.5 on 2025-03-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_investigator_grant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchgrant',
            old_name='type',
            new_name='grant_type',
        ),
        migrations.AlterField(
            model_name='investigator',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='researchgrant',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='researchgrant',
            name='funds_provided',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='researchgrant',
            name='year_of_award',
            field=models.PositiveIntegerField(),
        ),
    ]
