# Generated by Django 5.1.5 on 2025-03-04 06:41

import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_rename_type_researchgrant_grant_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_title', models.CharField(max_length=255)),
                ('awardee_name', models.CharField(max_length=255)),
                ('awarding_agency', models.CharField(max_length=255)),
                ('award_year', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Institution', 'Institution'), ('Teacher', 'Teacher'), ('Research Scholar', 'Research Scholar'), ('Student', 'Student')], max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='awards/', validators=[project.models.validate_file_size, project.models.validate_file_extension])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='project.department')),
            ],
        ),
    ]
