# Generated by Django 5.1.5 on 2025-03-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_awardrecognition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patenter_name', models.CharField(max_length=255)),
                ('patent_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('award_year', models.PositiveIntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='patents/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='project.department')),
            ],
        ),
    ]
