# Generated by Django 5.1.5 on 2025-03-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_patent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhDAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_name', models.CharField(max_length=255)),
                ('guides', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('registration_year', models.PositiveIntegerField()),
                ('award_year', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phds', to='project.department')),
            ],
        ),
    ]
