# Generated by Django 5.1.5 on 2025-03-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_phdaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdaward',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='phdaward/'),
        ),
    ]
