# Generated by Django 5.1.5 on 2025-03-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
