# Generated by Django 5.1.5 on 2025-03-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_userprofile_is_department_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_department_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_scholar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_teacher',
        ),
    ]
