# Generated by Django 5.1.5 on 2025-03-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_userprofile_is_department_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('num_applications', models.PositiveIntegerField()),
                ('num_seats', models.PositiveIntegerField()),
                ('demand_ratio', models.FloatField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
            ],
        ),
    ]
