# Generated by Django 5.1.5 on 2025-03-15 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_demandratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandratio',
            name='demand_ratio',
        ),
        migrations.AddField(
            model_name='demandratio',
            name='num_students_admitted',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandratio',
            name='programme_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandratio',
            name='programme_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandratio',
            name='academic_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='demandratio',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_ratios', to='project.department'),
        ),
    ]
