# Generated by Django 5.1.5 on 2025-03-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_remove_demandratio_demand_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of the Paper')),
                ('authors', models.TextField(verbose_name='Name of the Author(s)')),
                ('journal', models.CharField(max_length=255, verbose_name='Name of the Journal')),
                ('year', models.PositiveIntegerField(verbose_name='Year of Publication')),
                ('issn', models.CharField(max_length=15, verbose_name='ISSN Number')),
                ('ugc_link', models.URLField(blank=True, null=True, verbose_name='UGC Recognition Link')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_papers', to='project.department', verbose_name='Department')),
            ],
        ),
    ]
