# Generated by Django 5.1.5 on 2025-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_researchpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='research_paper/'),
        ),
    ]
