# Generated by Django 5.1.5 on 2025-03-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_researchpaper_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='Title of the Book/Chapter')),
                ('paper_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the Paper')),
                ('proceedings_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the Proceedings')),
                ('conference_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of the Conference')),
                ('national_international', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=50, verbose_name='National / International')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Year of Publication')),
                ('isbn_issn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN/ISSN')),
                ('affiliating_institute', models.CharField(blank=True, max_length=255, null=True, verbose_name='Affiliating Institute')),
                ('publisher', models.CharField(max_length=255, verbose_name='Publisher')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher', verbose_name='Name of the Teacher')),
            ],
        ),
    ]
