# Generated by Django 5.1.5 on 2025-03-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_bookchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('programme_name', models.CharField(max_length=255)),
                ('sc_earmarked', models.IntegerField(default=0)),
                ('st_earmarked', models.IntegerField(default=0)),
                ('obc_earmarked', models.IntegerField(default=0)),
                ('gen_earmarked', models.IntegerField(default=0)),
                ('others_earmarked', models.IntegerField(default=0)),
                ('sc_admitted', models.IntegerField(default=0)),
                ('st_admitted', models.IntegerField(default=0)),
                ('obc_admitted', models.IntegerField(default=0)),
                ('gen_admitted', models.IntegerField(default=0)),
                ('others_admitted', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='project.department')),
            ],
        ),
    ]
