# Generated by Django 5.1.5 on 2025-03-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_admittedstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_year', models.CharField(max_length=255, verbose_name='Qualification and Year of Obtaining')),
                ('is_research_guide', models.BooleanField(default=False, verbose_name='Recognised as Research Guide')),
                ('year_of_recognition', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Recognition as Research Guide')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_records', to='project.teacher', verbose_name='Teacher Name')),
            ],
        ),
    ]
