# Generated by Django 5.1.5 on 2025-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_teacherrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default=1, max_length=255, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='pan',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='PAN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Researcher', 'Researcher')], max_length=100, verbose_name='Designation'),
        ),
    ]
