# Generated by Django 5.1.5 on 2025-03-20 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_teacher_department_teacher_pan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherServingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_year', models.PositiveIntegerField(verbose_name='Appointment Year')),
                ('nature_of_appointment', models.CharField(max_length=255, verbose_name='Nature of Appointment')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('is_serving', models.BooleanField(default=True, verbose_name='Is Still Serving?')),
                ('last_year_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last Year of Service')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_posts', to='project.teacher', verbose_name='Teacher')),
            ],
        ),
    ]
