# Generated by Django 5.1.5 on 2025-03-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
