# Generated by Django 5.1.5 on 2025-03-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_remove_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTimeTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_year', models.CharField(max_length=255, verbose_name='Qualification (Ph.D./D.M/M.Ch./D.N.B Superspeciality/D.Sc./D’Lit.) and Year of Obtaining')),
                ('is_research_guide', models.BooleanField(default=False, verbose_name='Whether Recognised as Research Guide')),
                ('year_of_recognition', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Recognition as Research Guide')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher', verbose_name='Name of Full-Time Teacher')),
            ],
        ),
    ]
