# Generated by Django 5.1.5 on 2025-03-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_fulltimeteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAgainstSanctionedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_appointment', models.PositiveIntegerField(verbose_name='Year of Appointment')),
                ('nature_of_appointment', models.CharField(choices=[('Against Sanctioned Post', 'Against Sanctioned Post'), ('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=255, verbose_name='Nature of Appointment')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Total Years of Experience in the Same Institution')),
                ('still_serving', models.CharField(max_length=255, verbose_name='Is the teacher still serving / Last year of service')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher', verbose_name='Full-Time Teacher')),
            ],
        ),
    ]
