# Generated by Django 5.1.5 on 2025-03-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_teacheragainstsanctionedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheragainstsanctionedpost',
            name='last_year_of_service',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Last Year of Service'),
        ),
    ]
