# Generated by Django 5.1.5 on 2025-03-22 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_teacheragainstsanctionedpost_last_year_of_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_code', models.CharField(max_length=50, unique=True)),
                ('programme_name', models.CharField(max_length=255)),
                ('year_of_introduction', models.IntegerField()),
                ('cbcs_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('year_of_cbcs_implementation', models.IntegerField(blank=True, null=True)),
                ('year_of_revision', models.IntegerField(blank=True, null=True)),
                ('content_update_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('document_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='project.department')),
            ],
        ),
    ]
