# Generated by Django 5.1.5 on 2025-03-22 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Course')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('year_of_introduction', models.PositiveIntegerField(verbose_name='Year of Introduction')),
                ('activities', models.TextField(verbose_name='Employability/Skill Development Activities')),
                ('document', models.FileField(blank=True, null=True, upload_to='course_documents/', verbose_name='Relevant Document')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department', verbose_name='Department')),
            ],
        ),
    ]
