# Generated by Django 5.1.5 on 2025-03-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueAddedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('year_of_offering', models.PositiveIntegerField(verbose_name='Year of Offering')),
                ('times_offered', models.PositiveIntegerField(default=1, verbose_name='Number of Times Offered')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration (e.g., 30 Hours)')),
                ('students_enrolled', models.PositiveIntegerField(verbose_name='Students Enrolled')),
                ('students_completed', models.PositiveIntegerField(verbose_name='Students Completed')),
                ('document', models.FileField(blank=True, null=True, upload_to='course_documents/', verbose_name='Supporting Document')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='project.department', verbose_name='Department')),
            ],
        ),
    ]
