# Generated by Django 5.1.5 on 2025-03-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_valueaddedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=100, verbose_name='Programme Name')),
                ('programme_code', models.CharField(max_length=20, unique=True, verbose_name='Programme Code')),
                ('students', models.TextField(verbose_name='List of Students')),
                ('document', models.FileField(blank=True, null=True, upload_to='project_documents/', verbose_name='Supporting Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.department', verbose_name='Department')),
            ],
        ),
    ]
