# Generated by Django 5.1.5 on 2025-03-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_studentproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='programme_code',
            field=models.CharField(max_length=20, verbose_name='Programme Code'),
        ),
        migrations.AlterField(
            model_name='valueaddedcourse',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Course Code'),
        ),
    ]
